
# Site settings

url: "https://github.com/VincentBonhomme/personal-jekyll-theme.git"

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"

baseurl: /vincentbonhomme.io

google-tracking-id: "<YOUR GOOGLE TRACKING ID>"

#############
# HTML Head #
#############

author: "Vincent Bonhomme"
lang: "Fr"
title: "{Vincent Bonhomme}"
favicon:
description: "Blog and website of VincentBonhomme, Web designer."
keywords: "smith, jones, personal, jekyll, theme"

################
# Intro layout #
################

black-favicon: False
background-img: "https://github.com/VincentBonhomme/vincentbonhomme.io/img/home-2.jpg"
me-img: "vincentbonhomme.io/img/profil.png"

##############################
# Dynamic Text on the header #
##############################

dynamic-typing: True
shuffle: True	# Shuffle the lines.
loop: True
loop-count:	False # Set False for infinite loop, or set any number for finite loop.
type-speed:	10		# Default 10
start-delay: 200	# Default 200
delete-delay: 5000	# Default 5000
lines:			# You can add HTML Tags in the Text
  - text: "Hi there! "
  - text: "Here're some informations about me!"

########
# Blog #
########

post-preview-words: 128

paginate: 5

fb-share: True
twitter-share: True
reddit-share: True
disqus-shortname: ""

###############
# Life Events #
###############

events:
  - image: "/img/career/workflow.png"
    date: "December 2014 - Today"
    description: " Freelance web designer/front end developer."
  - image: "/img/career/logo-cl.png"
    date: "March 2015 - Today"
    description: "Launching of Roads Clothing Department : at Roads, we have decided to release a clothing label to support and develop our webzine. All our garments are produced in limited series and fully manufactured in Paris. You can see our e-shop (wich I designed) and the collection at this [link](http://www.roadsboutique.com/ 'link'){:target='_blank'}."
  - image: "/img/career/le-wagon.png"
    date: "September 2014 - December 2014"
    description: "Alumni of a fullstack bootcamp at [Le Wagon](http://www.lewagon.com/ 'Le Wagon'){:target='_blank'} (french coding school). Learning of html and css (Sass/less), ruby & Rails, javascript (jquery) and git/Github "
  - image: "/img/career/logo-roads-news.png"
    date: "September 2012 - Today"
    description: "CEO, Journalist (music and cinema), web designer and web master of [Roads Magazine](http://roadsmag.com/ 'Roads Magazine'){:target='_blank'}, a cultural and political independant webzine"
  - image: "/img/career/web-tech.jpg"
    date: "April 2012 - October 2012"
    description: "Journalist for [Web & Tech](http://web-tech.fr/ 'Web & Tech'){:target='_blank'}, a french pure-player specialized in high-tech and web culture"
  - image: "/img/career/iscpa.png"
    date: "September 2011 - September 2014"
    description: "Obtaining of a Licence in Journalism at ISCPA PARIS (Institut Supérieur des Médias)"

# First image of the Career timeline
career-img: "/img/career/time.jpg"

##################
# Contact layout #
##################

email: "vincent.vbonhomme@gmail.com"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://www.facebook.com/vincent.bonhomme.56"
  - title: "twitter"
    url: "https://twitter.com/bonhommevincent"
  - title: "github"
    url: "https://github.com/VincentBonhomme"


############
# 404 page #
############

404-img: "/img/tv.jpeg"

################################################################################

# Tread carefully if you want to change the variables below this point!

# Navigation bar links
# Blog link in the blog and post pages will point to the blog.html#blog
# In the default page it will point to the preview of the last post

pages_list:
  About: 'about'
  career: 'career'
  Contact: 'contact'

# Pagination path
paginate_path: "blog/page:num"

# Enable minification SASS
sass:
  style: compressed

# Exclusion list from the generated _site
exclude: ["Rakefile", "LICENSE", "readme.markdown", "vendor"]
